version: '3.8'
services:
    saaslide-api:
        container_name: api-saaslide
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=development