executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  Hello-Saaslide:
    executor: node/default
    steps:
      - run:
          name: Hello Saaslide
          command: |
            echo 'Hello Saaslide'
  Install-node-example:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
orbs:
  node: circleci/node@4.0.1
version: 2.1
workflows:
  SaaSlide-api:
    jobs:
      - Hello-Saaslide