executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  Hello-Saaslide:
    executor: node/default
    steps:
      - run:
          name: Hello Saaslide
          command: |
            echo 'Hello Saaslide'
  Install-node-example:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          label: Use nvm for a specific node version...
          command: |
            set +e
            # if you need to install it, uncomment the following
            # wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash &&  sudo /opt/circleci/.nvm/nvm.sh
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v18.5.0            
            npm install -g yarn 
      - run: node --version
  Verify-eslint:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          override-ci-command: yarn install
      - run:
          command: |
            yarn run eslint
  Unit-test:
      executor: my-executor
      steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          override-ci-command: yarn install
      
orbs:
  node: circleci/node@4.0.1
version: 2.1
workflows:
  SaaSlide-api:
    jobs:
      - Hello-Saaslide
      - Install-node-example
      - Unit-test
      - Verify-eslint