executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  Hello-Saaslide:
    executor: node/default
    steps:
      - run:
          name: Hello Saaslide
          command: |
            echo 'Hello Saaslide'
  Install-node-example:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
  Verify-eslint:
    executor: my-executor
    steps:
      - checkout
      - run:
          command: |
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
                echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
                echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - node/install:
          install-yarn: true
      - node/install-packages:
          override-ci-command: yarn install
      - run:
          command: |
            yarn run eslint
  Unit-test:
      executor: my-executor
      steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          override-ci-command: yarn install
      
orbs:
  node: circleci/node@4.0.1
version: 2.1
workflows:
  SaaSlide-api:
    jobs:
      - Hello-Saaslide
      - Install-node-example
      - Unit-test
      - Verify-eslint