executors:
  my-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  - run:
  Hello-Saaslide:
    executor: node/default
    steps:
      - run:
          name: Hello Saaslide
          command: |
            echo 'Hello Saaslide'
  Install-node-example:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  Verify-eslint:
    executor: my-executor
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          override-ci-command: yarn install
      - run:
          command: |
            yarn run eslint
  Unit-test:
      executor: my-executor
      steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: nvm install 18.5.0
      - node/install-packages:
          override-ci-command: yarn install
      
orbs:
  node: circleci/node@4.0.1
version: 2.1
workflows:
  SaaSlide-api:
    jobs:
      - Hello-Saaslide
      - Install-node-example
      - Unit-test
      - Verify-eslint