apiVersion: v1
kind: PersistentVolume # Le volume alloué 
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "public/pdfToPng"
