apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-pdf
  labels:
    type: local
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  accessModes: 
    - ReadWriteOnce