name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.6'
      
      - name: Install Dependencies
        run: yarn install
        
      # - name: Test Lint
      #   run: yarn run eslint