name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
    

    env:
      GH_ACCESS_TOKEN: ${{ secrets.GITHUB_SECRET }}
      JWT_SIGN_SECRET: ${{ secrets.JWT_SIGN_SECRET }}
      PORT: 4000
      SOCKET_PORT: 4001
      URI_DB: ${{ secrets.URI_DB }}
      NAME_DB: ${{ secrets.NAME_DB }}
      PASSWORD_DB: ${{ secrets.PASSWORD_DB }}

    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.6'

      - name: Install Dependencies
        run: yarn install

      - name: Run Test
        run: yarn run test

      - name: Run Lint
        run: yarn run eslint